{% set name = "awkward-pandas" %}
{% set version = "2023.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/awkward_pandas/awkward_pandas-{{ version }}.tar.gz
  sha256: 56b7b735241502423ac9afb49db0dd3bb5905a51a53cdfe476e9d4316a975fde

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.8.0
    - hatch-vcs
    - toml
  run:
    - python >=3.8
    - awkward >=2.0.0
    - pandas >=1.2
    - pyarrow >=7.0.0

test:
  imports:
    - awkward_pandas
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://awkward-pandas.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Connecting awkward-array and Pandas.
  description: |
    An Awkward extension array for use with Pandas.
  doc_url: https://awkward-pandas.readthedocs.io/
  dev_url: https://github.com/intake/awkward-pandas/

extra:
  recipe-maintainers:
    - jpivarski
    - douglasdavis
    - martindurant
