{% set name = "akimbo" %}
{% set version = "2024.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/akimbo/akimbo-{{ version }}.tar.gz
  sha256: 274eb5edbea3b3e9f069bb447d13fe66eadc4578310d8d3630ac200ed42bacc4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.8.0
    - hatch-vcs
    - toml
  run:
    - python >=3.8
    - awkward >=2.0.0
    - pyarrow >=7.0.0

test:
  imports:
    - akimbo
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://akimbo.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: For when your data won't fit in your dataframe
  description: |
    The akimbo project provides a Dataframe accessor for various backend, that enable analysis of nested, 
    non-tabular data in workflows.
  doc_url: https://akimbo.readthedocs.io/
  dev_url: https://github.com/intake/akimbo/

extra:
  recipe-maintainers:
    - jpivarski
    - douglasdavis
    - martindurant
